#install: skip

language: c

#compiler:
#        - gcc
#        - clang

os:
        - linux
        - osx
        - freebsd

branches:
#        - master
        - dev

script:
        - touch aclocal.m4 Makefile.in src/Makefile.in doc/Makefile.in test/Makefile.in config.h.in
        - sleep 1
        - touch configure
        - sleep 1
        - ./configure --enable-public-interface
        - sleep 1
        - touch doc/libsecrm.info
        - sleep 1
        - make
