.\"	Process this file with groff -man -Tascii foo.3
.\"
.TH libsecrm 3 GNU/Linux "User's Manual"

.SH NAME
libsecrm \- Ensuring secure removal of data.

.SH SYNOPSIS
~/.bash_profile:

.B export LD_PRELOAD=/usr/local/lib/libsecrm.so

and/or

/etc/ld.so.preload:

.B /usr/local/lib/libsecrm.so

.SH DESCRIPTION
The libsecrm library ensures that data removed from files is removed securely
(just like using the 'shred' program), by intercepting necessary library calls:
unlink, unlinkat, remove (obvious), fopen, freopen, fdopen (with
the mode parameter containing 'w'), truncate, ftruncate,
open, openat (with O_TRUNC passed in flags), creat and the 64-bit versions of these. The library
.B MUST NOT
be setuid(root). This would allow anyone to delete files from system directories.

Libsecrm partially also takes care about memory security - some of the memory
allocation functions are intercepted (namely: malloc, posix_memalign, valloc, memalign,
brk, sbrk), and the allocated memory is wiped before
passing it to the calling program.


.SH NOTES
The file and command given in the synopsis section may be different on shells other than BASH.

.SH FILES
The /proc filesystem is used to check if a file to be wiped is already opened.

${sysconfdir} is /usr/local/etc unless defined otherwise.

${sysconfdir}/libsecrm.progban - which programs want to run normally (partial names are enough). The
/proc filesystem must be mounted in order for this to work right now.

${sysconfdir}/libsecrm.fileban - which files not to wipe (partial names are enough)

Put each entry on its own line.

.SH AUTHOR
Bogdan 'bogdro' Drozdowski,
bogdandr /AT/ op . pl

bogdro /AT/ rudy . mif . pg . gda . pl

[EN] http://libsecrm.sf.net

[PL] http://libsecrm.sf.net/index-pl.php

[EN] http://rudy.mif.pg.gda.pl/~bogdro/soft/

[EN] http://rudy.mif.pg.gda.pl/~bogdro/inne/

[PL] http://rudy.mif.pg.gda.pl/~bogdro/

.SH THANKS TO

  - Manuel Arriaga for libtrash, parts of which are used here
  - Colin Plumb, for the great 'shred' program, parts of which are used here.
    The 'shred' utility is:
 	Copyright (C) 1999-2006 Free Software Foundation, Inc.
 	Copyright (C) 1997, 1998, 1999 Colin Plumb.
  - The authors of Libsafe for the great piece of software, parts of which
    are used here. Libsafe is:
 	Copyright (C) 2002 Avaya Labs, Avaya Inc.
 	Copyright (C) 1999 Bell Labs, Lucent Technologies.
 	Copyright (C) Arash Baratloo, Timothy Tsai, and Navjot Singh.
  - The authors of the "fuser" utility, parts of which are used here. Fuser is:
 	Based on fuser.c Copyright (C) 1993-2005 Werner Almesberger and Craig Small
 	Completely re-written
 	Copyright (C) 2005 Craig Small


.SH "SEE ALSO"
.BR shred (1),
.B info wipefreespace

The 'info' documentation is more descriptive and is the main one. Type

.B 	info libsecrm

to read it.

